os: windows
language: node_js
node_js:
  "8"
install:
  yarn release
script:
  - yarn test
  - IF $TRAVIS_BRANCH == "master" node node_modules/tfx-cli/_build/tfx-cli.js extension publish --vsix *.vsix --token $VS_TOKEN
